name: CI/CD Flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Generate module jars
        run: gradle build --exclude-task test
      - name: Build & Push Docker user-service
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          context: .
          image: ivandvurechenskiy/calculator-server
          tags: latest
          registry: docker.io
          dockerfile: ./Dockerfile
          username: ivandvurechenskiy
          password: ${{ secrets.DOCKER_PASSWORD }}
